/* Generated by tools/gen_vtbl_arity.py - do not edit.
 *
 * Bytes each COM method pops on return, one entry per vtable slot,
 * so a stub can clean the stack the way the real method would. */

/* ID3D11BlendStateVtbl: 8 methods */
static const unsigned char kArity_ID3D11BlendStateVtbl[8] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	2, /* GetDevice */
	4, /* GetPrivateData */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	2, /* GetDesc */
};

/* ID3D11BufferVtbl: 11 methods */
static const unsigned char kArity_ID3D11BufferVtbl[11] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	2, /* GetDevice */
	4, /* GetPrivateData */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	2, /* GetType */
	2, /* SetEvictionPriority */
	1, /* GetEvictionPriority */
	2, /* GetDesc */
};

/* ID3D11DepthStencilStateVtbl: 8 methods */
static const unsigned char kArity_ID3D11DepthStencilStateVtbl[8] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	2, /* GetDevice */
	4, /* GetPrivateData */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	2, /* GetDesc */
};

/* ID3D11DepthStencilViewVtbl: 9 methods */
static const unsigned char kArity_ID3D11DepthStencilViewVtbl[9] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	2, /* GetDevice */
	4, /* GetPrivateData */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	2, /* GetResource */
	2, /* GetDesc */
};

/* ID3D11Device1Vtbl: 50 methods */
static const unsigned char kArity_ID3D11Device1Vtbl[50] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	4, /* CreateBuffer */
	4, /* CreateTexture1D */
	4, /* CreateTexture2D */
	4, /* CreateTexture3D */
	4, /* CreateShaderResourceView */
	4, /* CreateUnorderedAccessView */
	4, /* CreateRenderTargetView */
	4, /* CreateDepthStencilView */
	6, /* CreateInputLayout */
	5, /* CreateVertexShader */
	5, /* CreateGeometryShader */
	10, /* CreateGeometryShaderWithStreamOutput */
	5, /* CreatePixelShader */
	5, /* CreateHullShader */
	5, /* CreateDomainShader */
	5, /* CreateComputeShader */
	2, /* CreateClassLinkage */
	3, /* CreateBlendState */
	3, /* CreateDepthStencilState */
	3, /* CreateRasterizerState */
	3, /* CreateSamplerState */
	3, /* CreateQuery */
	3, /* CreatePredicate */
	3, /* CreateCounter */
	3, /* CreateDeferredContext */
	4, /* OpenSharedResource */
	3, /* CheckFormatSupport */
	4, /* CheckMultisampleQualityLevels */
	2, /* CheckCounterInfo */
	10, /* CheckCounter */
	4, /* CheckFeatureSupport */
	4, /* GetPrivateData */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	1, /* GetFeatureLevel */
	1, /* GetCreationFlags */
	1, /* GetDeviceRemovedReason */
	2, /* GetImmediateContext */
	2, /* SetExceptionMode */
	1, /* GetExceptionMode */
	2, /* GetImmediateContext1 */
	3, /* CreateDeferredContext1 */
	3, /* CreateBlendState1 */
	3, /* CreateRasterizerState1 */
	8, /* CreateDeviceContextState */
	4, /* OpenSharedResource1 */
	5, /* OpenSharedResourceByName */
};

/* ID3D11DeviceContext1Vtbl: 134 methods */
static const unsigned char kArity_ID3D11DeviceContext1Vtbl[134] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	2, /* GetDevice */
	4, /* GetPrivateData */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	4, /* VSSetConstantBuffers */
	4, /* PSSetShaderResources */
	4, /* PSSetShader */
	4, /* PSSetSamplers */
	4, /* VSSetShader */
	4, /* DrawIndexed */
	3, /* Draw */
	6, /* Map */
	3, /* Unmap */
	4, /* PSSetConstantBuffers */
	2, /* IASetInputLayout */
	6, /* IASetVertexBuffers */
	4, /* IASetIndexBuffer */
	6, /* DrawIndexedInstanced */
	5, /* DrawInstanced */
	4, /* GSSetConstantBuffers */
	4, /* GSSetShader */
	2, /* IASetPrimitiveTopology */
	4, /* VSSetShaderResources */
	4, /* VSSetSamplers */
	2, /* Begin */
	2, /* End */
	5, /* GetData */
	3, /* SetPredication */
	4, /* GSSetShaderResources */
	4, /* GSSetSamplers */
	4, /* OMSetRenderTargets */
	8, /* OMSetRenderTargetsAndUnorderedAccessViews */
	4, /* OMSetBlendState */
	3, /* OMSetDepthStencilState */
	4, /* SOSetTargets */
	1, /* DrawAuto */
	3, /* DrawIndexedInstancedIndirect */
	3, /* DrawInstancedIndirect */
	4, /* Dispatch */
	3, /* DispatchIndirect */
	2, /* RSSetState */
	3, /* RSSetViewports */
	3, /* RSSetScissorRects */
	9, /* CopySubresourceRegion */
	3, /* CopyResource */
	7, /* UpdateSubresource */
	4, /* CopyStructureCount */
	3, /* ClearRenderTargetView */
	3, /* ClearUnorderedAccessViewUint */
	3, /* ClearUnorderedAccessViewFloat */
	5, /* ClearDepthStencilView */
	2, /* GenerateMips */
	3, /* SetResourceMinLOD */
	2, /* GetResourceMinLOD */
	6, /* ResolveSubresource */
	3, /* ExecuteCommandList */
	4, /* HSSetShaderResources */
	4, /* HSSetShader */
	4, /* HSSetSamplers */
	4, /* HSSetConstantBuffers */
	4, /* DSSetShaderResources */
	4, /* DSSetShader */
	4, /* DSSetSamplers */
	4, /* DSSetConstantBuffers */
	4, /* CSSetShaderResources */
	5, /* CSSetUnorderedAccessViews */
	4, /* CSSetShader */
	4, /* CSSetSamplers */
	4, /* CSSetConstantBuffers */
	4, /* VSGetConstantBuffers */
	4, /* PSGetShaderResources */
	4, /* PSGetShader */
	4, /* PSGetSamplers */
	4, /* VSGetShader */
	4, /* PSGetConstantBuffers */
	2, /* IAGetInputLayout */
	6, /* IAGetVertexBuffers */
	4, /* IAGetIndexBuffer */
	4, /* GSGetConstantBuffers */
	4, /* GSGetShader */
	2, /* IAGetPrimitiveTopology */
	4, /* VSGetShaderResources */
	4, /* VSGetSamplers */
	3, /* GetPredication */
	4, /* GSGetShaderResources */
	4, /* GSGetSamplers */
	4, /* OMGetRenderTargets */
	7, /* OMGetRenderTargetsAndUnorderedAccessViews */
	4, /* OMGetBlendState */
	3, /* OMGetDepthStencilState */
	3, /* SOGetTargets */
	2, /* RSGetState */
	3, /* RSGetViewports */
	3, /* RSGetScissorRects */
	4, /* HSGetShaderResources */
	4, /* HSGetShader */
	4, /* HSGetSamplers */
	4, /* HSGetConstantBuffers */
	4, /* DSGetShaderResources */
	4, /* DSGetShader */
	4, /* DSGetSamplers */
	4, /* DSGetConstantBuffers */
	4, /* CSGetShaderResources */
	4, /* CSGetUnorderedAccessViews */
	4, /* CSGetShader */
	4, /* CSGetSamplers */
	4, /* CSGetConstantBuffers */
	1, /* ClearState */
	1, /* Flush */
	1, /* GetType */
	1, /* GetContextFlags */
	3, /* FinishCommandList */
	10, /* CopySubresourceRegion1 */
	8, /* UpdateSubresource1 */
	2, /* DiscardResource */
	2, /* DiscardView */
	6, /* VSSetConstantBuffers1 */
	6, /* HSSetConstantBuffers1 */
	6, /* DSSetConstantBuffers1 */
	6, /* GSSetConstantBuffers1 */
	6, /* PSSetConstantBuffers1 */
	6, /* CSSetConstantBuffers1 */
	6, /* VSGetConstantBuffers1 */
	6, /* HSGetConstantBuffers1 */
	6, /* DSGetConstantBuffers1 */
	6, /* GSGetConstantBuffers1 */
	6, /* PSGetConstantBuffers1 */
	6, /* CSGetConstantBuffers1 */
	3, /* SwapDeviceContextState */
	5, /* ClearView */
	4, /* DiscardView1 */
};

/* ID3D11InputLayoutVtbl: 7 methods */
static const unsigned char kArity_ID3D11InputLayoutVtbl[7] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	2, /* GetDevice */
	4, /* GetPrivateData */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
};

/* ID3D11PixelShaderVtbl: 7 methods */
static const unsigned char kArity_ID3D11PixelShaderVtbl[7] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	2, /* GetDevice */
	4, /* GetPrivateData */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
};

/* ID3D11QueryVtbl: 9 methods */
static const unsigned char kArity_ID3D11QueryVtbl[9] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	2, /* GetDevice */
	4, /* GetPrivateData */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	1, /* GetDataSize */
	2, /* GetDesc */
};

/* ID3D11RasterizerStateVtbl: 8 methods */
static const unsigned char kArity_ID3D11RasterizerStateVtbl[8] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	2, /* GetDevice */
	4, /* GetPrivateData */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	2, /* GetDesc */
};

/* ID3D11RenderTargetViewVtbl: 9 methods */
static const unsigned char kArity_ID3D11RenderTargetViewVtbl[9] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	2, /* GetDevice */
	4, /* GetPrivateData */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	2, /* GetResource */
	2, /* GetDesc */
};

/* ID3D11SamplerStateVtbl: 8 methods */
static const unsigned char kArity_ID3D11SamplerStateVtbl[8] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	2, /* GetDevice */
	4, /* GetPrivateData */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	2, /* GetDesc */
};

/* ID3D11ShaderResourceViewVtbl: 9 methods */
static const unsigned char kArity_ID3D11ShaderResourceViewVtbl[9] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	2, /* GetDevice */
	4, /* GetPrivateData */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	2, /* GetResource */
	2, /* GetDesc */
};

/* ID3D11Texture2DVtbl: 11 methods */
static const unsigned char kArity_ID3D11Texture2DVtbl[11] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	2, /* GetDevice */
	4, /* GetPrivateData */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	2, /* GetType */
	2, /* SetEvictionPriority */
	1, /* GetEvictionPriority */
	2, /* GetDesc */
};

/* ID3D11VertexShaderVtbl: 7 methods */
static const unsigned char kArity_ID3D11VertexShaderVtbl[7] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	2, /* GetDevice */
	4, /* GetPrivateData */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
};

/* IDXGIAdapter1Vtbl: 11 methods */
static const unsigned char kArity_IDXGIAdapter1Vtbl[11] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	4, /* GetPrivateData */
	3, /* GetParent */
	3, /* EnumOutputs */
	2, /* GetDesc */
	3, /* CheckInterfaceSupport */
	2, /* GetDesc1 */
};

/* IDXGIDevice1Vtbl: 14 methods */
static const unsigned char kArity_IDXGIDevice1Vtbl[14] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	4, /* GetPrivateData */
	3, /* GetParent */
	2, /* GetAdapter */
	6, /* CreateSurface */
	4, /* QueryResourceResidency */
	2, /* SetGPUThreadPriority */
	2, /* GetGPUThreadPriority */
	2, /* SetMaximumFrameLatency */
	2, /* GetMaximumFrameLatency */
};

/* IDXGIFactory2Vtbl: 25 methods */
static const unsigned char kArity_IDXGIFactory2Vtbl[25] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	4, /* GetPrivateData */
	3, /* GetParent */
	3, /* EnumAdapters */
	3, /* MakeWindowAssociation */
	2, /* GetWindowAssociation */
	4, /* CreateSwapChain */
	3, /* CreateSoftwareAdapter */
	3, /* EnumAdapters1 */
	1, /* IsCurrent */
	1, /* IsWindowedStereoEnabled */
	7, /* CreateSwapChainForHwnd */
	6, /* CreateSwapChainForCoreWindow */
	3, /* GetSharedResourceAdapterLuid */
	4, /* RegisterStereoStatusWindow */
	3, /* RegisterStereoStatusEvent */
	2, /* UnregisterStereoStatus */
	4, /* RegisterOcclusionStatusWindow */
	3, /* RegisterOcclusionStatusEvent */
	2, /* UnregisterOcclusionStatus */
	5, /* CreateSwapChainForComposition */
};

/* IDXGIOutputVtbl: 19 methods */
static const unsigned char kArity_IDXGIOutputVtbl[19] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	4, /* GetPrivateData */
	3, /* GetParent */
	2, /* GetDesc */
	5, /* GetDisplayModeList */
	4, /* FindClosestMatchingMode */
	1, /* WaitForVBlank */
	3, /* TakeOwnership */
	1, /* ReleaseOwnership */
	2, /* GetGammaControlCapabilities */
	2, /* SetGammaControl */
	2, /* GetGammaControl */
	2, /* SetDisplaySurface */
	2, /* GetDisplaySurfaceData */
	2, /* GetFrameStatistics */
};

/* IDXGISwapChain1Vtbl: 29 methods */
static const unsigned char kArity_IDXGISwapChain1Vtbl[29] = {
	3, /* QueryInterface */
	1, /* AddRef */
	1, /* Release */
	4, /* SetPrivateData */
	3, /* SetPrivateDataInterface */
	4, /* GetPrivateData */
	3, /* GetParent */
	3, /* GetDevice */
	3, /* Present */
	4, /* GetBuffer */
	3, /* SetFullscreenState */
	3, /* GetFullscreenState */
	2, /* GetDesc */
	6, /* ResizeBuffers */
	2, /* ResizeTarget */
	2, /* GetContainingOutput */
	2, /* GetFrameStatistics */
	2, /* GetLastPresentCount */
	2, /* GetDesc1 */
	2, /* GetFullscreenDesc */
	2, /* GetHwnd */
	3, /* GetCoreWindow */
	4, /* Present1 */
	1, /* IsTemporaryMonoSupported */
	2, /* GetRestrictToOutput */
	2, /* SetBackgroundColor */
	2, /* GetBackgroundColor */
	2, /* SetRotation */
	2, /* GetRotation */
};

