"""Emit the stack-cleanup size of every COM method we stub.

A stdcall callee pops its own arguments, so a stub standing in for a method it
does not implement has to pop exactly as many bytes as the real one would. A
single one-size-fits-all stub cannot: it pops too few, the caller returns
through whatever argument is left on the stack, and the process jumps to
garbage. The counts have to be right, and there are enough of them that
counting by hand is how you get one wrong.

So read them out of the headers the build already compiles against. That keeps
the table honest by construction - if the headers move, this moves with them.

Run from the d3d9_sw directory:
    python tools/gen_vtbl_arity.py > vtbl_arity.h
"""

import re
import sys
import os

HDR = r"C:\zig\lib\libc\include\any-windows-any"
HEADERS = ["unknwn.h", "dxgi.h", "dxgi1_2.h", "d3d11.h", "d3d11_1.h"]

# Types wider than a register. Everything else - pointers, enums, handles, and
# the small integers that stdcall widens on the way onto the stack - is one
# slot. A parameter this does not recognise is reported rather than assumed.
WIDE = {
    "UINT64", "INT64", "ULONGLONG", "LONGLONG", "DWORDLONG", "double",
    "LARGE_INTEGER", "ULARGE_INTEGER", "DWORD64",
}
NARROW = {
    "UINT", "INT", "DWORD", "LONG", "ULONG", "WORD", "SHORT", "USHORT",
    "BYTE", "UINT8", "UINT16", "UINT32", "INT32", "CHAR", "BOOL", "WINBOOL",
    "FLOAT", "float", "SIZE_T", "HRESULT", "REFIID", "REFGUID", "HANDLE",
    "HWND", "HMONITOR", "HDC", "LPCSTR", "LPCWSTR", "void", "SECURITY_ATTRIBUTES",
}

unknown = set()


def slots(param):
    """Stack slots one parameter occupies, in dwords."""
    param = param.strip()
    if not param or param == "void":
        return 0
    if "*" in param or "[" in param:
        return 1  # any pointer, however decorated
    words = [w for w in re.split(r"[\s&]+", param) if w]
    words = [w for w in words if w not in ("const", "struct", "enum", "unsigned", "signed")]
    if not words:
        return 1
    base = words[0]
    if base in WIDE:
        return 2
    if base in NARROW or base.startswith(("D3D", "DXGI", "D3D11", "D3D10")):
        return 1
    unknown.add(base)
    return 1


def parse(text, table):
    """Collect every '<Name>Vtbl' and the arity of each of its methods."""
    for m in re.finditer(r"typedef struct (\w+Vtbl)\s*\{(.*?)\n\}\s*\1", text, re.S):
        name, body = m.group(1), m.group(2)
        methods = []
        for f in re.finditer(r"\(\s*STDMETHODCALLTYPE\s*\*\s*(\w+)\s*\)\s*\((.*?)\)\s*;", body, re.S):
            mname, args = f.group(1), f.group(2)
            args = re.sub(r"/\*.*?\*/", "", args, flags=re.S)
            n = sum(slots(a) for a in args.split(","))
            methods.append((mname, n))
        if methods:
            table[name] = methods


def main():
    table = {}
    for h in HEADERS:
        p = os.path.join(HDR, h)
        if not os.path.exists(p):
            sys.stderr.write("missing header: %s\n" % p)
            continue
        with open(p, "r", encoding="utf-8", errors="replace") as fh:
            parse(fh.read(), table)

    # Only emit the vtables this wrapper actually hands out.
    with open("d3d11_sw.c", "r", encoding="utf-8", errors="replace") as fh:
        src = fh.read()
    wanted = sorted(set(re.findall(r"static\s+(\w+Vtbl)\s+k\w+Vtbl\s*;", src)))

    out = []
    out.append("/* Generated by tools/gen_vtbl_arity.py - do not edit.")
    out.append(" *")
    out.append(" * Bytes each COM method pops on return, one entry per vtable slot,")
    out.append(" * so a stub can clean the stack the way the real method would. */")
    out.append("")
    for name in wanted:
        if name not in table:
            sys.stderr.write("no header definition for %s\n" % name)
            continue
        methods = table[name]
        out.append("/* %s: %d methods */" % (name, len(methods)))
        out.append("static const unsigned char kArity_%s[%d] = {" % (name, len(methods)))
        for mname, n in methods:
            out.append("\t%d, /* %s */" % (n, mname))
        out.append("};")
        out.append("")
    print("\n".join(out))

    if unknown:
        sys.stderr.write("unrecognised parameter types: %s\n" % ", ".join(sorted(unknown)))
    for name in wanted:
        if name in table:
            sys.stderr.write("%-34s %3d methods\n" % (name, len(table[name])))


main()
