#!/usr/bin/env python3
"""Copy initialized PE .data / .rdata into wholesale/pe_data.bin.

Never maps the PE VSz hole (33 MB). Raw .data is ~106 KB. Host copies
slices into named DAT_* at boot via host_pe_copy(va, dst, n).

  python tools/pack_pe_data.py
"""
from __future__ import annotations

import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = Path(
    r"F:\Ragnarok Battle Offline + Ex1-3\ENGLISH PATCH\ENGLISH PATCH\RBO_Ex3.exe"
)
OUT_BIN = ROOT / "wholesale" / "pe_data.bin"
OUT_H = ROOT / "host" / "include" / "host_pe_data.h"


def pe_sections(data: bytes) -> list[tuple[bytes, int, int, int, int]]:
    e_lfanew = struct.unpack_from("<I", data, 0x3C)[0]
    nsect = struct.unpack_from("<H", data, e_lfanew + 6)[0]
    opt_size = struct.unpack_from("<H", data, e_lfanew + 20)[0]
    sect0 = e_lfanew + 24 + opt_size
    out = []
    for i in range(nsect):
        off = sect0 + i * 40
        name = data[off : off + 8].split(b"\0", 1)[0]
        vsz, va, rsz, raw = struct.unpack_from("<IIII", data, off + 8)
        out.append((name, vsz, va, rsz, raw))
    return out


def main() -> int:
    exe = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_EXE
    if not exe.is_file():
        print(f"error: no PE at {exe}", file=sys.stderr)
        return 1
    data = exe.read_bytes()
    image_base = 0x00400000
    blob = None
    va = 0
    rsz = 0
    for name, vsz, rva, rawsz, raw in pe_sections(data):
        print(
            f"  {name.decode('ascii', 'replace'):8} RVA={rva:08x} "
            f"VSz={vsz} raw={rawsz} file={raw}"
        )
        if name == b".data":
            blob = data[raw : raw + rawsz]
            va = image_base + rva
            rsz = rawsz
            print(f".data initialized {rsz} bytes at VA {va:08x}..{va + rsz:08x}")
    if not blob:
        print("error: no .data", file=sys.stderr)
        return 1
    OUT_BIN.parent.mkdir(parents=True, exist_ok=True)
    OUT_BIN.write_bytes(blob)
    OUT_H.write_text(
        "/* Generated by tools/pack_pe_data.py. Do not edit. */\n"
        "#ifndef HOST_PE_DATA_H\n"
        "#define HOST_PE_DATA_H\n"
        f"#define HOST_PE_DATA_VA 0x{va:08x}u\n"
        f"#define HOST_PE_DATA_SIZE {rsz}u\n"
        "#endif\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {OUT_BIN} ({rsz} bytes)")
    print(f"wrote {OUT_H}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
